### ISSUE TITLE
请问怎么调用这个api？

### ISSUE THREAD

**Issue by Mr-huangyh** [allanpk716/WanKeYunApi#1]
小白，不是很懂，想学！是要另外搭建一个服务端口去调用吗，但是怎么开放端口呢？

**Comment by allanpk716** [comment]
看 OneThingHelper.py ，里面有调用的代码，最后注释掉了而已。

**Comment by allanpk716** [comment]
> 小白，不是很懂，想学！是要另外搭建一个服务端口去调用吗，但是怎么开放端口呢？

看 OneThingHelper.py ，里面有调用的代码，最后注释掉了而已。
端口会自动分配的，这个不需要上层考虑。
